title: "AMINU USMAN MODIBBO - MEP Engineer"
description: "Experienced in HVAC, Plumbing, Fire Protection, and Electrical Design."
author: 
  name: "USMAN AMINU MODIBBO "
  email: "USSY.AMEEN100@GMAIL.COM"
  linkedin: "https://www.linkedin.com/in/USSYAMEEN/"
  github: "https://github.com/AUMODIBBO"
  location: "KADUNA, Nigeria "
